name: requirements-txt

on: [ push ]

jobs:
  create-requirements-txt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kivy
    - name: Create requirements.txt
      run: |
        pip freeze > requirements.txt
    - name: Commit und Push requirements.txt
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add requirements.txt
        git diff --exit-code || git commit -m "Update requirements.txt" --allow-empty
        git push
